# Generated by Django 2.1.2 on 2018-10-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0002_remove_currencyrate_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
